; Permission levels: 0=Guest, 1=Normal, 2=Debug, 3=Engineer, 4=Root

[ConfigPage]
IdlePurgeConfiguration = 1
PneumaticValvePressureConfiguration = 1
SH85PeriodicSelfCheckConfiguration = 1
SH85SelfCheckConfiguration = 1
PurgeFlowConfiguration = 1
DeviceEnableConfiguration = 1
DeviceInfoConfiguration = 2

[DebugPage]
FirmwareConfig = 2
FirmwareUpdate = 2
VEFCGasTypeConfiguration = 3
UIRefreshTimeConfiguration = 3
HumidityOffsetConfiguration = 3
VEFCFlowUnitMediumStatus = 3
BoardEnableStatus = 3
FoupInVacuumExtractionEnable = 3
FoupInAutoPurgeEnable = 3
