INCLUDEPATH += $$PWD

HEADERS += \
    $$PWD/scheduler_task.h \
    $$PWD/scheduler.h \
    $$PWD/tasks/disk_pressure_cleanup_task/disk_pressure_cleanup_task.h \
    $$PWD/tasks/alarmlogquerytask/alarmlogquerytask.h \
    $$PWD/tasks/communicatelogquerytask/communicatelogquerytask.h \
    $$PWD/tasks/foup_in_va_extr_enable/foupinvaextrenabletask.h \
    $$PWD/tasks/monitor_data_task/monitor_data_task.h \
    $$PWD/tasks/monitor_data_task/monitor_data_task_logger.h \
    $$PWD/tasks/vefc_sensor_monitor_task/vefc_sensor_monitor_types.h \
    $$PWD/tasks/vefc_sensor_monitor_task/vefc_sensor_monitor_daily_stats.h \
    $$PWD/tasks/vefc_sensor_monitor_task/vefc_sensor_monitor_task.h \
    $$PWD/tasks/vefc_sensor_monitor_task/vefc_sensor_monitor_device_selector.h \
    $$PWD/tasks/vefc_sensor_monitor_task/vefc_sensor_monitor_round_context.h \
    $$PWD/tasks/vefc_sensor_monitor_task/vefc_sensor_monitor_log_service.h \
    $$PWD/tasks/vefc_sensor_monitor_task/vefc_sensor_monitor_round_runner.h \
    $$PWD/tasks/vefc_sensor_monitor_task/vefc_sensor_monitor_task_logger.h \
    $$PWD/tasks/operationlogquerytask/operationlogquerytask.h \
    $$PWD/tasks/send_command_task/send_command_task.h \
    $$PWD/tasks/init_check_task/init_check_task.h \
    $$PWD/tasks/network_status_task/network_status_task.h \
    $$PWD/tasks/network_status_task/network_status_task_logger.h \
    $$PWD/tasks/network_status_task/network_status_task_qrcode_logger.h \
    $$PWD/tasks/electric_cabinet_serial_port_status_task/electric_cabinet_serial_port_status_task.h \
    $$PWD/tasks/electric_cabinet_serial_port_status_task/electric_cabinet_serial_port_status_task_logger.h \
    $$PWD/tasks/set_firmware_config_task/set_firmware_config_task.h \
    $$PWD/tasks/firmware_upgrade_task/firmware_upgrade_task.h \
    $$PWD/tasks/set_idle_purge_task/set_idle_purge_task.h \
    $$PWD/tasks/set_pneumatic_valve_pressure_task/set_pneumatic_valve_pressure_task.h \
    $$PWD/tasks/sh85selfchecktask/sh85_self_check_task.h \
    $$PWD/tasks/sh85selfchecktask/sh85_periodic_self_check_task.h \
    $$PWD/tasks/sh85selfchecktask/sh85_periodic_self_check_task2.h \
    $$PWD/tasks/sh85selfchecktask/sh85_periodic_self_check_task3.h \
    $$PWD/tasks/sh85selfchecktask/sh85_self_check_types.h \
    $$PWD/tasks/sh85selfchecktask/sh85_self_check_round_context.h \
    $$PWD/tasks/sh85selfchecktask/sh85_self_check_device_selector.h \
    $$PWD/tasks/sh85selfchecktask/sh85_self_check_round_runner.h \
    $$PWD/tasks/sh85selfchecktask/sh85_self_check_log_service.h \
    $$PWD/tasks/sh85selfchecktask/boot_delay_timer.h \
    $$PWD/tasks/sh85selfchecktask/sh85_self_check_log_helper.h \
    $$PWD/tasks/set_humidity_offset_task/set_humidity_offset_task.h \
    $$PWD/tasks/set_device_info_task/set_device_info_task.h \
    $$PWD/tasks/set_purge_flow_task/set_purge_flow_task.h \
    $$PWD/tasks/set_vefc_gas_type_task/set_vefc_gas_type_task.h \
    $$PWD/tasks/set_ui_refresh_time_task/set_ui_refresh_time_task.h \
    $$PWD/tasks/read_vefc_flow_unit_medium_status_task/read_vefc_flow_unit_medium_status_task.h \
    $$PWD/tasks/read_device_version_task/read_device_version_task.h \
    $$PWD/tasks/alarm_dispatch_task/alarm_dispatch_task.h \
    $$PWD/tasks/alarm_dispatch_task/alarm_dispatch_task_logger.h \
    $$PWD/tasks/operation_dispatch_task/operation_dispatch_task.h \
    $$PWD/tasks/user_management_task/user_management_task.h

SOURCES += \
    $$PWD/scheduler.cpp \
    $$PWD/tasks/disk_pressure_cleanup_task/disk_pressure_cleanup_task.cpp \
    $$PWD/tasks/alarmlogquerytask/alarmlogquerytask.cpp \
    $$PWD/tasks/communicatelogquerytask/communicatelogquerytask.cpp \
    $$PWD/tasks/monitor_data_task/monitor_data_task.cpp \
    $$PWD/tasks/monitor_data_task/monitor_data_task_logger.cpp \
    $$PWD/tasks/vefc_sensor_monitor_task/vefc_sensor_monitor_device_selector.cpp \
    $$PWD/tasks/vefc_sensor_monitor_task/vefc_sensor_monitor_daily_stats.cpp \
    $$PWD/tasks/vefc_sensor_monitor_task/vefc_sensor_monitor_round_context.cpp \
    $$PWD/tasks/vefc_sensor_monitor_task/vefc_sensor_monitor_log_service.cpp \
    $$PWD/tasks/vefc_sensor_monitor_task/vefc_sensor_monitor_round_runner.cpp \
    $$PWD/tasks/vefc_sensor_monitor_task/vefc_sensor_monitor_task.cpp \
    $$PWD/tasks/vefc_sensor_monitor_task/vefc_sensor_monitor_task_logger.cpp \
    $$PWD/tasks/operationlogquerytask/operationlogquerytask.cpp \
    $$PWD/tasks/send_command_task/send_command_task.cpp \
    $$PWD/tasks/init_check_task/init_check_task.cpp \
    $$PWD/tasks/network_status_task/network_status_task.cpp \
    $$PWD/tasks/network_status_task/network_status_task_logger.cpp \
    $$PWD/tasks/network_status_task/network_status_task_qrcode_logger.cpp \
    $$PWD/tasks/electric_cabinet_serial_port_status_task/electric_cabinet_serial_port_status_task.cpp \
    $$PWD/tasks/electric_cabinet_serial_port_status_task/electric_cabinet_serial_port_status_task_logger.cpp \
    $$PWD/tasks/set_firmware_config_task/set_firmware_config_task.cpp \
    $$PWD/tasks/firmware_upgrade_task/firmware_upgrade_task.cpp \
    $$PWD/tasks/set_idle_purge_task/set_idle_purge_task.cpp \
    $$PWD/tasks/set_pneumatic_valve_pressure_task/set_pneumatic_valve_pressure_task.cpp \
    $$PWD/tasks/sh85selfchecktask/sh85_self_check_task.cpp \
    $$PWD/tasks/sh85selfchecktask/sh85_periodic_self_check_task.cpp \
    $$PWD/tasks/sh85selfchecktask/sh85_periodic_self_check_task2.cpp \
    $$PWD/tasks/sh85selfchecktask/sh85_periodic_self_check_task3.cpp \
    $$PWD/tasks/sh85selfchecktask/sh85_self_check_round_context.cpp \
    $$PWD/tasks/sh85selfchecktask/sh85_self_check_device_selector.cpp \
    $$PWD/tasks/sh85selfchecktask/sh85_self_check_round_runner.cpp \
    $$PWD/tasks/sh85selfchecktask/sh85_self_check_log_service.cpp \
    $$PWD/tasks/sh85selfchecktask/boot_delay_timer.cpp \
    $$PWD/tasks/sh85selfchecktask/sh85_self_check_log_helper.cpp \
    $$PWD/tasks/set_humidity_offset_task/set_humidity_offset_task.cpp \
    $$PWD/tasks/set_device_info_task/set_device_info_task.cpp \
    $$PWD/tasks/set_purge_flow_task/set_purge_flow_task.cpp \
    $$PWD/tasks/set_vefc_gas_type_task/set_vefc_gas_type_task.cpp \
    $$PWD/tasks/set_ui_refresh_time_task/set_ui_refresh_time_task.cpp \
    $$PWD/tasks/read_vefc_flow_unit_medium_status_task/read_vefc_flow_unit_medium_status_task.cpp \
    $$PWD/tasks/read_device_version_task/read_device_version_task.cpp \
    $$PWD/tasks/alarm_dispatch_task/alarm_dispatch_task.cpp \
    $$PWD/tasks/alarm_dispatch_task/alarm_dispatch_task_logger.cpp \
    $$PWD/tasks/operation_dispatch_task/operation_dispatch_task.cpp \
    $$PWD/tasks/user_management_task/user_management_task.cpp
